# Generated by Django 3.1.5 on 2021-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_auto_20210114_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(max_length=1000),
        ),
    ]
