# Generated by Django 3.1.5 on 2021-01-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_auto_20210114_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
