# Generated by Django 3.1.5 on 2021-01-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_auto_20210118_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_categories',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='product_categories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DemoApp.category'),
        ),
        migrations.AddField(
            model_name='product_categories',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DemoApp.product'),
        ),
    ]
